language: java
jdk: openjdk8
install: true
script: mvn clean install javadoc:aggregate
notifications:
  irc:
    channels:
      - "chat.freenode.net#stripes"
    on_success: always
    on_failure: always
    use_notice: true
