/*
 * Copyright 2001-2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 
package net.sourceforge.stripes.util;

import java.io.Serializable;
import org.apache.log4j.Logger;
import org.apache.log4j.Priority;
import org.apache.log4j.Level;
import org.slf4j.helpers.MarkerIgnoringBase;
import org.slf4j.helpers.MessageFormatter;

/**
 * Implementation of {@link Log} that maps directly to a
 * <strong>Logger</strong> for log4J version 1.2.
 * <p>
 * Initial configuration of the corresponding Logger instances should be done
 * in the usual manner, as outlined in the Log4J documentation.
 * <p>
 * The reason this logger is distinct from the 1.3 logger is that in version 1.2
 * of Log4J:
 * <ul>
 * <li>class Logger takes Priority parameters not Level parameters.
 * <li>class Level extends Priority
 * </ul>
 * Log4J1.3 is expected to change Level so it no longer extends Priority, which is
 * a non-binary-compatible change. The class generated by compiling this code against
 * log4j 1.2 will therefore not run against log4j 1.3.
 *
 * @author <a href="mailto:sanders@apache.org">Scott Sanders</a>
 * @author Rod Waldhoff
 * @author Robert Burrell Donkin
 * @version $Id: Log4JLogger.java 370672 2006-01-19 23:52:23Z skitching $
 */

@SuppressWarnings({ "serial", "deprecation" })
public class Log4JLogger extends MarkerIgnoringBase implements org.slf4j.Logger, Serializable {

    // ------------------------------------------------------------- Attributes

    /** The fully qualified name of the Log4JLogger class.
     * 
     *  ADP - This is the only change from the original in slf4j-api */
    private static final String FQCN = net.sourceforge.stripes.util.Log.class.getName();
    
    /** Log to this logger */
    private transient Logger logger = null;

    /** Logger name */
    private String name = null;

    private static Priority traceLevel;
    
    // ------------------------------------------------------------
    // Static Initializer.
    //
    // Note that this must come after the static variable declarations
    // otherwise initialiser expressions associated with those variables
    // will override any settings done here.
    //
    // Verify that log4j is available, and that it is version 1.2.
    // If an ExceptionInInitializerError is generated, then LogFactoryImpl
    // will treat that as meaning that the appropriate underlying logging
    // library is just not present - if discovery is in progress then
    // discovery will continue.
    // ------------------------------------------------------------

    static {
        if (!Priority.class.isAssignableFrom(Level.class)) {
            // nope, this is log4j 1.3, so force an ExceptionInInitializerError
            throw new InstantiationError("Log4J 1.2 not available");
        }
        
        // Releases of log4j1.2 >= 1.2.12 have Priority.TRACE available, earlier
        // versions do not. If TRACE is not available, then we have to map
        // calls to Log.trace(...) onto the DEBUG level.
        
        try {
            traceLevel = (Priority) Level.class.getDeclaredField("TRACE").get(null);
        } catch(Exception ex) {
            // ok, trace not available
            traceLevel = Priority.DEBUG;
        }
    }
    
    // ------------------------------------------------------------ Constructor

    public Log4JLogger() {
    }

    /**
     * Base constructor.
     */
    public Log4JLogger(String name) {
        this.name = name;
        this.logger = getLogger();
    }

    /** For use with a log4j factory.
     */
    public Log4JLogger(Logger logger) {
        this.name = logger.getName();
        this.logger=logger;
    }

    // --------------------------------------------------------- 
    // Implementation
    //
    // Note that in the methods below the Priority class is used to define
    // levels even though the Level class is supported in 1.2. This is done
    // so that at compile time the call definitely resolves to a call to
    // a method that takes a Priority rather than one that takes a Level.
    // 
    // The Category class (and hence its subclass Logger) in version 1.2 only
    // has methods that take Priority objects. The Category class (and hence
    // Logger class) in version 1.3 has methods that take both Priority and
    // Level objects. This means that if we use Level here, and compile
    // against log4j 1.3 then calls would be bound to the versions of
    // methods taking Level objects and then would fail to run against
    // version 1.2 of log4j.
    // --------------------------------------------------------- 

    /**
     * Returns the name of this logger instance.
     */
    public String getName() {
        return getLogger().getName();
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.TRACE</code>.
     * When using a log4j version that does not support the <code>TRACE</code>
     * level, the message will be logged at the <code>DEBUG</code> level.
     *
     * @param message to log
     * @see org.slf4j.Logger#trace(Object)
     */
    public void trace(String message) {
        getLogger().log(FQCN, traceLevel, message, null);
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.TRACE</code>.
     * When using a log4j version that does not support the <code>TRACE</code>
     * level, the message will be logged at the <code>DEBUG</code> level.
     *
     * @param message to log
     * @param t log this cause
     * @see org.slf4j.Logger#trace(Object, Throwable)
     */
    public void trace(String message, Throwable t) {
        getLogger().log(FQCN, traceLevel, message, t);
    }

    /**
     * Log a message at level TRACE according to the specified format and
     * argument.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for level TRACE. </p>
     *
     * @param format the format string
     * @param arg  the argument
     */
    public void trace(String format, Object arg) {
        if (isTraceEnabled()) {
            String msgStr = MessageFormatter.format(format, arg);
            getLogger().log(FQCN, traceLevel, msgStr, null);
        }
    }

    /**
     * Log a message at level TRACE according to the specified format and
     * arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the TRACE level. </p>
     *
     * @param format the format string
     * @param arg1  the first argument
     * @param arg2  the second argument
     */
    public void trace(String format, Object arg1, Object arg2) {
        if (isTraceEnabled()) {
            String msgStr = MessageFormatter.format(format, arg1, arg2);
            logger.log(FQCN, traceLevel, msgStr, null);
        }
    }
    
    /**
     * Log a message at level TRACE according to the specified format and
     * arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the TRACE level. </p>
     *
     * @param format the format string
     * @param argArray an array of arguments
     */
    public void trace(String format, Object[] argArray) {
        if (isTraceEnabled()) {
            String msgStr = MessageFormatter.arrayFormat(format, argArray);
            logger.log(FQCN, traceLevel, msgStr, null);
        }
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.DEBUG</code>.
     *
     * @param message to log
     * @see org.slf4j.Logger#debug(Object)
     */
    public void debug(String message) {
        getLogger().log(FQCN, Priority.DEBUG, message, null);
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.DEBUG</code>.
     *
     * @param message to log
     * @param t log this cause
     * @see org.slf4j.Logger#debug(Object, Throwable)
     */
    public void debug(String message, Throwable t) {
        getLogger().log(FQCN, Priority.DEBUG, message, t);
    }

    /**
     * Log a message at level DEBUG according to the specified format and
     * argument.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for level DEBUG. </p>
     *
     * @param format the format string
     * @param arg  the argument
     */
    public void debug(String format, Object arg) {
        if (logger.isDebugEnabled()) {
            String msgStr = MessageFormatter.format(format, arg);
            logger.log(FQCN, Priority.DEBUG, msgStr, null);
        }
    }

    /**
     * Log a message at level DEBUG according to the specified format and
     * arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the DEBUG level. </p>
     *
     * @param format the format string
     * @param arg1  the first argument
     * @param arg2  the second argument
     */
    public void debug(String format, Object arg1, Object arg2) {
        if (logger.isDebugEnabled()) {
            String msgStr = MessageFormatter.format(format, arg1, arg2);
            logger.log(FQCN, Priority.DEBUG, msgStr, null);
        }
    }
    
    /**
     * Log a message at level DEBUG according to the specified format and
     * arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the DEBUG level. </p>
     *
     * @param format the format string
     * @param argArray an array of arguments
     */
    public void debug(String format, Object[] argArray) {
        if (logger.isDebugEnabled()) {
            String msgStr = MessageFormatter.arrayFormat(format, argArray);
            logger.log(FQCN, Priority.DEBUG, msgStr, null);
        }
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.INFO</code>.
     *
     * @param message to log
     * @see org.slf4j.Logger#info(Object)
     */
    public void info(String message) {
        getLogger().log(FQCN, Priority.INFO, message, null);
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.INFO</code>.
     *
     * @param message to log
     * @param t log this cause
     * @see org.slf4j.Logger#info(Object, Throwable)
     */
    public void info(String message, Throwable t) {
        getLogger().log(FQCN, Priority.INFO, message, t);
    }

    /**
     * Log a message at level INFO according to the specified format and
     * argument.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the INFO level. </p>
     *
     * @param format the format string
     * @param arg  the argument
     */
    public void info(String format, Object arg) {
        if (logger.isInfoEnabled()) {
            String msgStr = MessageFormatter.format(format, arg);
            logger.log(FQCN, Level.INFO, msgStr, null);
        }
    }

    /**
     * Log a message at the INFO level according to the specified format
     * and arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the INFO level. </p>
     *
     * @param format the format string
     * @param arg1  the first argument
     * @param arg2  the second argument
     */
    public void info(String format, Object arg1, Object arg2) {
        if (logger.isInfoEnabled()) {
            String msgStr = MessageFormatter.format(format, arg1, arg2);
            logger.log(FQCN, Level.INFO, msgStr, null);
        }
    }

    /**
     * Log a message at level INFO according to the specified format and
     * arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the INFO level. </p>
     *
     * @param format the format string
     * @param argArray an array of arguments
     */
    public void info(String format, Object[] argArray) {
        if (logger.isInfoEnabled()) {
            String msgStr = MessageFormatter.arrayFormat(format, argArray);
            logger.log(FQCN, Level.INFO, msgStr, null);
        }
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.WARN</code>.
     *
     * @param message to log
     * @see org.slf4j.Logger#warn(Object)
     */
    public void warn(String message) {
        getLogger().log(FQCN, Priority.WARN, message, null);
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.WARN</code>.
     *
     * @param message to log
     * @param t log this cause
     * @see org.slf4j.Logger#warn(Object, Throwable)
     */
    public void warn(String message, Throwable t) {
        getLogger().log(FQCN, Priority.WARN, message, t);
    }

    /**
     * Log a message at the WARN level according to the specified
     * format and argument.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the WARN level. </p>
     *
     * @param format the format string
     * @param arg  the argument
     */
    public void warn(String format, Object arg) {
        if (logger.isEnabledFor(Level.WARN)) {
            String msgStr = MessageFormatter.format(format, arg);
            logger.log(FQCN, Level.WARN, msgStr, null);
        }
    }

    /**
     * Log a message at the WARN level according to the specified
     * format and arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the WARN level. </p>
     *
     * @param format the format string
     * @param arg1  the first argument
     * @param arg2  the second argument
     */
    public void warn(String format, Object arg1, Object arg2) {
        if (logger.isEnabledFor(Level.WARN)) {
            String msgStr = MessageFormatter.format(format, arg1, arg2);
            logger.log(FQCN, Level.WARN, msgStr, null);
        }
    }

    /**
     * Log a message at level WARN according to the specified format and
     * arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the WARN level. </p>
     *
     * @param format the format string
     * @param argArray an array of arguments
     */
    public void warn(String format, Object[] argArray) {
        if (logger.isEnabledFor(Level.WARN)) {
            String msgStr = MessageFormatter.arrayFormat(format, argArray);
            logger.log(FQCN, Level.WARN, msgStr, null);
        }
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.ERROR</code>.
     *
     * @param message to log
     * @see org.slf4j.Logger#error(Object)
     */
    public void error(String message) {
        getLogger().log(FQCN, Priority.ERROR, message, null);
    }

    /**
     * Logs a message with <code>org.apache.log4j.Priority.ERROR</code>.
     *
     * @param message to log
     * @param t log this cause
     * @see org.slf4j.Logger#error(Object, Throwable)
     */
    public void error(String message, Throwable t) {
        getLogger().log(FQCN, Priority.ERROR, message, t);
    }

    /**
     * Log a message at the ERROR level according to the specified
     * format and argument.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the ERROR level. </p>
     *
     * @param format the format string
     * @param arg  the argument
     */
    public void error(String format, Object arg) {
        if (logger.isEnabledFor(Level.ERROR)) {
            String msgStr = MessageFormatter.format(format, arg);
            logger.log(FQCN, Level.ERROR, msgStr, null);
        }
    }

    /**
     * Log a message at the ERROR level according to the specified
     * format and arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the ERROR level. </p>
     *
     * @param format the format string
     * @param arg1  the first argument
     * @param arg2  the second argument
     */
    public void error(String format, Object arg1, Object arg2) {
        if (logger.isEnabledFor(Level.ERROR)) {
            String msgStr = MessageFormatter.format(format, arg1, arg2);
            logger.log(FQCN, Level.ERROR, msgStr, null);
        }
    }

    /**
     * Log a message at level ERROR according to the specified format and
     * arguments.
     *
     * <p>This form avoids superfluous object creation when the logger
     * is disabled for the ERROR level. </p>
     *
     * @param format the format string
     * @param argArray an array of arguments
     */
    public void error(String format, Object[] argArray) {
        if (logger.isEnabledFor(Level.ERROR)) {
            String msgStr = MessageFormatter.arrayFormat(format, argArray);
            logger.log(FQCN, Level.ERROR, msgStr, null);
        }
    }

    /**
     * Return the native Logger instance we are using.
     */
    public Logger getLogger() {
        if (logger == null) {
            logger = Logger.getLogger(name);
        }
        return (this.logger);
    }

    /**
     * Check whether the Log4j Logger used is enabled for <code>DEBUG</code> priority.
     */
    public boolean isDebugEnabled() {
        return getLogger().isDebugEnabled();
    }

    /**
     * Check whether the Log4j Logger used is enabled for <code>ERROR</code> priority.
     */
    public boolean isErrorEnabled() {
        return getLogger().isEnabledFor(Priority.ERROR);
    }

    /**
     * Check whether the Log4j Logger used is enabled for <code>INFO</code> priority.
     */
    public boolean isInfoEnabled() {
        return getLogger().isInfoEnabled();
    }

    /**
     * Check whether the Log4j Logger used is enabled for <code>TRACE</code> priority.
     * When using a log4j version that does not support the TRACE level, this call
     * will report whether <code>DEBUG</code> is enabled or not.
     */
    public boolean isTraceEnabled() {
        return getLogger().isEnabledFor(traceLevel);
    }

    /**
     * Check whether the Log4j Logger used is enabled for <code>WARN</code> priority.
     */
    public boolean isWarnEnabled() {
        return getLogger().isEnabledFor(Priority.WARN);
    }
}
